/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef echo_CONSTANTS_H
#define echo_CONSTANTS_H

#include "echo_types.h"

namespace bfd { namespace harpc { namespace demo {

class echoConstants {
 public:
  echoConstants();

};

extern const echoConstants g_echo_constants;

}}} // namespace

#endif
