/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "echo_constants.h"

namespace bfd { namespace harpc { namespace demo {

const echoConstants g_echo_constants;

echoConstants::echoConstants() {
}

}}} // namespace

