
if(COMMAND cmake_policy)
	cmake_policy(SET CMP0003 NEW)
endif(COMMAND cmake_policy)

if(COMMAND cmake_policy)
	cmake_policy(SET CMP0011 NEW)
endif(COMMAND cmake_policy)

GET_FILENAME_COMPONENT( RESEARCH_BUILD_DIR "${PROJECT_SOURCE_DIR}" ABSOLUTE )
GET_FILENAME_COMPONENT( RESEARCH_ROOT_DIR "${RESEARCH_BUILD_DIR}/../" ABSOLUTE )
GET_FILENAME_COMPONENT( RESEARCH_CMAKE_DIR "${RESEARCH_ROOT_DIR}/cmake/" ABSOLUTE )

MESSAGE( STATUS "DEBUG SOURCE_DIR: ${PROJECT_SOURCE_DIR}" )
MESSAGE( STATUS "DEBUG BUILD_DIR: ${RESEARCH_BUILD_DIR}" )
MESSAGE( STATUS "DEBUG ROOT_DIR: ${RESEARCH_ROOT_DIR}" )
MESSAGE( STATUS "DEBUG: CMAKE_DIR: ${RESEARCH_CMAKE_DIR}" )

#ADD_CUSTOM_TARGET( deepclean COMMAND rm -rf "${RESEARCH_BUILD_DIR}/tmp" VERBATIM)

#
# Basic Utils
#
INCLUDE( ${RESEARCH_CMAKE_DIR}/Tools.cmake )

#demo thrift
ADD_DC_SERVICE("thrift/" "demo_thrift" thrift)

INCLUDE( ${RESEARCH_CMAKE_DIR}/demo_client.cmake )
INCLUDE( ${RESEARCH_CMAKE_DIR}/demo_service.cmake )

#
# Main Project
#
